#!/bin/bash

# Ralph New Project - Create a new Ralph project from template
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/lib/utils.sh"

show_help() {
    cat << HELPEOF
Ralph New Project - Create a new project from template

Usage: $0 <project-name>

Arguments:
    project-name    Name for the new Ralph project (lowercase, no spaces)

Examples:
    $0 signals
    $0 pagination
    $0 my-feature

This will create:
    ralph/projects/<project-name>/
    ├── prd.md           # PRD template to fill out
    ├── prd.json         # Empty (will be generated by convert.sh)
    ├── requirements.md  # Technical requirements (populated by convert.sh)
    ├── progress.txt     # Progress log
    ├── PROMPT.md        # Standard Ralph prompt
    └── logs/            # Execution logs

HELPEOF
}

main() {
    local project_name="$1"
    
    # Validate arguments
    if [[ -z "$project_name" ]]; then
        log "ERROR" "Project name is required"
        show_help
        exit 1
    fi
    
    # Sanitize project name
    project_name=$(echo "$project_name" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
    
    local project_dir="$SCRIPT_DIR/projects/$project_name"
    
    # Check if project already exists
    if [[ -d "$project_dir" ]]; then
        log "ERROR" "Project '$project_name' already exists at: $project_dir"
        exit 1
    fi
    
    log "INFO" "Creating new Ralph project: $project_name"
    
    # Create project directory structure
    mkdir -p "$project_dir/logs"
    
    # Copy templates
    cp "$SCRIPT_DIR/templates/prd-template.md" "$project_dir/prd.md"
    cp "$SCRIPT_DIR/templates/PROMPT.md" "$project_dir/PROMPT.md"
    cp "$SCRIPT_DIR/templates/requirements.md" "$project_dir/requirements.md"

    # Create empty prd.json with proper structure
    cat > "$project_dir/prd.json" << PRDEOF
{
  "branchName": "ralph/$project_name",
  "userStories": []
}
PRDEOF
    
    # Create progress file with Codebase Patterns section at top
    cat > "$project_dir/progress.txt" << EOF
# Progress Log: $project_name

Created: $(date '+%Y-%m-%d %H:%M:%S')

## Notes
- Edit prd.md with your requirements
- Run: ./ralph/convert.sh $project_name
- Then: ./ralph/start.sh $project_name

EOF
    
    # Create status.json
    cat > "$project_dir/status.json" << EOF
{
    "project": "$project_name",
    "created_at": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
    "status": "created",
    "loop_count": 0,
    "stories_complete": 0,
    "stories_total": 0
}
EOF
    
    log "SUCCESS" "🎉 Project '$project_name' created!"
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "📋 IMPORTANT: How to build your PRD"
    echo ""
    echo "   The PRD template is just a starting point. To build a great PRD:"
    echo ""
    echo "   1. Open the PRD in your AI of choice (Claude, Codex, Opus, etc.)"
    echo "   2. Describe what you want to build"
    echo "   3. ⚡ ASK THE AI TO INTERVIEW YOU ⚡"
    echo ""
    echo "   The interview is the MOST IMPORTANT part. Let the AI ask questions"
    echo "   about your feature, edge cases, requirements, and constraints."
    echo "   This produces a much better PRD than writing it yourself."
    echo ""
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""
    echo "Next steps:"
    echo "  1. Build your PRD with AI (see above):"
    echo "     ${EDITOR:-code} $project_dir/prd.md"
    echo ""
    echo "  2. Convert PRD to JSON tasks:"
    echo "     ./ralph/convert.sh $project_name"
    echo ""
    echo "  3. Start the Ralph loop:"
    echo "     ./ralph/start.sh $project_name"
    echo ""
    echo "Project created at: $project_dir"
}

# Handle command line arguments
case "${1:-}" in
    -h|--help)
        show_help
        exit 0
        ;;
    "")
        show_help
        exit 1
        ;;
    *)
        main "$@"
        ;;
esac
